### ISSUE TITLE
Desarrollo de las principales funciones

### ISSUE THREAD

**Issue by davizinho5** [aigora/twE100_2122-grupo-carlos-victor-y-gabriel#4]
Debéis implementar las principales funciones del programa.
Esta implementación puede tener cambios en la versión definitiva. Aún no es necesario que realice todas las funcionalidades previstas.
Se recomienda el uso de librerías propias para alojar estas funciones.

**Comment by Gabriel-S-J** [comment]
Se han definido las funciones de las pruebas y del menú
