### ISSUE TITLE
Recuperación del trabajo

### ISSUE THREAD

**Issue by davizinho5** [aigora/twE100_2122-grupo-carlos-victor-y-gabriel#9]
Tenéis una nueva issue para resumir las cosas que debéis mejorar de cara a aprobar el trabajo.

- Debéis limpiar el repositorio y dejar UN SOLO FICHERO PRINCIPAL y no dejar basura en el repositorio. No me vale con que hagáis una carpeta de "Entrega final".
- Debéis aseguraros de usar una librería vuestra, aunque sea sencilla.
- Si podéis añadir escritura de ficheros para algo, aunque sea sencillo, mejor.

**Ojo**, se comprobará la posible copia de código en la entrega. 

Para que cuente el trabajo como aprobado a cada integrante, debéis participar en las mejoras, no vale que lo acabe una persona y el resto no haga nada. Quién no participe, su nota no se actualizará. En vuestro caso, además, hay un integrante que prácticamente no ha hecho nada del trabajo hasta la fecha, y así ha quedado reflejado en la nota. Si no cambia nada para extraordinaria no aprobará aunque entre los demás si acabéis el trabajo.

**FECHAS**: si entregáis antes del lunes 13 de Junio a las 15, puedo dejaros la nota puesta en convocatoria ordinaria. Si no, el límite de entrega de la recuperación del trabajo en convocatoria extraordinaria sería el día del examen a las 23:59.

Cuando acabéis, cerrad esta issue para dejarlo marcado.

**Comment by victorsenfernandez** [comment]
Ya hemos realizado las mejoras, las hemos explicado en la wiki apartado de mejoras.

**Comment by davizinho5** [comment]
Buenas, 
Doy las mejoras como buenas. Eso sí, hay una cosa que necesita mejorar: el diagrama de flujo. 
Al haber añadido la escritura del fichero, falta esa parte de añadir al diagrama. 
Os doy el trabajo como aprobado (5,85 de nota), pero quiero que subáis el **diagrama de flujo correcto**. 
Cerrad esta issue cuando lo tengáis.

**Comment by victorsenfernandez** [comment]
Completado
